# Generated by Django 2.1.1 on 2018-09-23 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 18, 18, 6, 773695)),
        ),
    ]
